### ISSUE TITLE
[Question] Why is the path to acme.sh hardcoded?

### ISSUE THREAD

**Issue by schadom** [Froxlor/Froxlor#1002]
See in https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L41 ?

Would be nice if it could be changed from within the administrator settings in the panel.
Does something speak against it?

Thanks

**Comment by d00p** [comment]
Mainly because when we changed from another way of implementation to acme.sh froxlor also takes care of the Installation of acme.sh if not found (see https://github.com/Froxlor/Froxlor/blob/149c0935fa0b32c1c484f328a1a7700a6f7c59fe/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php#L600) and this is the default installation target directory

**Comment by d00p** [comment]
A setting of course could be added for that
