### ISSUE TITLE
Let's Encrypt disabled and broken on all domains after upgrade to 2.0

### ISSUE THREAD

**Issue by halfgaar** [Froxlor/Froxlor#1098]
Since upgrading to 2.0.10-1, the SSL certificates for the hosted websites are no longer Let's Encrypt. They are instead just copied to `/etc/ssl/froxlor/`. If I try to enable it on domains again, it says:

> The domains DNS does not include any of the chosen IP addresses. Let's Encrypt certificate generation not possible. 

(that should be "The domain's DNS")

But it's also not true. Then I disabled domain/IP validation in the settings, and then the 'tasks' job says:

```
/usr/bin/php -q /var/www/html/froxlor/bin/froxlor-cli froxlor:cron 'tasks'
Checking froxlor file permissions...OK
Running "tasks" job
[warning] Skipping Let's Encrypt generation for example.nl due to an enabled ssl_redirect
```

I don't know what that means. That doesn't seem to be reason not to do Let's Encrypt. Edit: hey, the domain suddenly worked. Confusing error message?

Debian version 11.6.

**Comment by d00p** [comment]
Known, already fixed in git, I'm sorry I'm currently more than busy and just dont have the time for enough testing before a new release. You can find the fix here: https://github.com/Froxlor/Froxlor/commit/67fc762eef98f29cbc3430a0efdea0621be6c58d

> [warning] Skipping Let's Encrypt generation for example.nl due to an enabled ssl_redirect
I don't know what that means. That doesn't seem to be reason not to do Let's Encrypt. Edit: hey, the domain suddenly worked. Confusing error message?

This is to avoid any kind of race condition
