### ISSUE TITLE
FR: More information for user on backup creation feature

### ISSUE THREAD

**Issue by patschi** [Froxlor/Froxlor#1152]
**Is your feature request related to a problem? Please describe.**
Without further details, it's hard to know when backups take place.

**Describe the solution you'd like**
The new backup feature is nice, but I'm missing a few essential information like when the backup is approx. scheduled/performed at. When creating a backup entry, it just says "It is being processed" but there is absolutely no indication when this is the case.

![image](https://github.com/Froxlor/Froxlor/assets/2029878/d3ade5d0-df8d-4387-bcc3-90310cfae9bd)

I guess the backup job is ran daily as per the cronjob settings within the Froxlor UI. This would be a great chance to retrieve the date there and show it on this specific page.

Additionally, it is not clear if the backup process is done once or automatically on a daily basis.

**Describe alternatives you've considered**
n/a

**Comment by envoyr** [comment]
Hello Patschi,

The "Backup" feature is not really new, but it has mostly functioned as a one-time export option for users.

Since there have been frequent requests for an enhanced backup function, I am currently working on a comprehensive rewrite for version 2.1 to address this.

The new implementation will offer more detailed information about when and how backups are created. Additionally, it will allow for regular automated backups, which will bring added value to both administrators and customers.

By the way, I will close this matter as it will be resolved as part of issue #1033. Feel free to provide feedback and continue the discussion there.

Best regards,
envoyr
