### ISSUE TITLE
libnss-mysql-bg Bug (no IPv6 Support)

### ISSUE THREAD

**Issue by Cellebyte** [Froxlor/Froxlor#420]
For Recreation.
---------------------
- libnss-mysql-bg on one Server
- Mysql Server on another Server
- assign ipv6 addresses to both Servers
- edit the libnss-mysql.config host string
 to the dns name or ipv6 address of the Mysql Server
`libnss-mysql: _nss_mysql_is_same_sockaddr: Unhandled sin_family` <<<- Error

Solution:
------------
- Add an alternative in the Switch Case from line 70 to 88
Their is no option for IPv6 so default case screws whole program.
Link to source code found on [Sourceforge](https://sourcecodebrowser.com/libnss-mysql-bg/1.5/mysql_8c_source.html)

**Comment by d00p** [comment]
Well, we are not libnss-mysql and cannot fix bugs in their code

**Comment by Cellebyte** [comment]
# libnss-mysql-bg-1.5-4
## IPv6 support for libnss-mysql-bg

- Addet IPv6 support
- Fix seg faulting on wrong query
- Fix a bug mentionend on Launchpad

## Fixed .deb file
- [libnss-mysql-bd_amd_64_BUILD.zip](https://github.com/Froxlor/Froxlor/files/911726/libnss-mysql-bd-amd_64_BUILD.zip)

## Original Repo
[Sourceforge libnss-mysql-bg](http://libnss-mysql.sourceforge.net/)

**Comment by Dessa** [comment]
i'll need the src deb for that so it can be properly integrated in the repo (need to rebuild for jessie+1 and possibly finally build it for the missing arches as well)

**Comment by Cellebyte** [comment]
# src

- it is on my account
- i will integrate it with travis
- you can clone everything

**Comment by Cellebyte** [comment]
@Dessa @d00p

**Comment by d00p** [comment]
No need to highlight, there are people sleeping at night you know...

**Comment by d00p** [comment]
Are you going to maintain that for longer?

**Comment by Cellebyte** [comment]
Don't know for now. You'll ship it with froxlor, so I'll think you distribute it.
I can fix bugs.
But not want to distribute the whole thing.
I have no time for this.

**Comment by Happy86** [comment]
* Just out of curiosity: Will the Froxlor (apt/...) repository[1] ship the patched version of libnss-mysql-bg? 
* And if so: How long will it take? 

Also I am not sure if the definition of "maintain" is clear: 
* Package maintenance should be done by those who can change the files on the mirror server (aka who can connect via ssh to the repository server[1] ;-). 
* Code maintenance: Since the project seems to be abandoned[2] I think every patch that fixes bugs (plural) should be welcome.

As far as I see it the currently distributed[1] version segfaults and it does not support IPv6 which should be mandatory since 1998[3]. I currently test the patched version on 3 Debian Servers (1x Wheezy, 2xJessie) and it works fine. 


[1] [http://debian.froxlor.org/](http://debian.froxlor.org/)
[2] [http://libnss-mysql.sourceforge.net/](http://libnss-mysql.sourceforge.net/)
[3] [https://www.ietf.org/rfc/rfc2460.txt](https://www.ietf.org/rfc/rfc2460.txt)

**Comment by d00p** [comment]
Don't know if you knew but WE are not the libnss-mysql maintainers and so not intend to be. Next version will come with the alternative libnss-extrausers. If we provide a Patches libnss-mysql ist unclear at the moment, reasons see first sentence.

**Comment by Happy86** [comment]
I knew that you are not the maintainers of the source code. 

But you provide a repository. And for me the definition of a package maintainer is someone that provides a package on a package repository. 

Obviously this is all volunteer work and there is no guarantee of code maintenance or updated packages. 

It would just be nice if you could take the work @Cellebyte and put it on your repository improving the lives of all Froxlor users in the meantime. 

So until it is clear if Froxlor does the switch to libnss-extrausers you could just upload the patched package (which does not segfault) to your apt repository. :-)

**Comment by schallertd** [comment]
I strongly recommend the deprecation of libnss-mysql* usage with the upcoming froxlor versions. Since the source seems to be unmaintained since 2005 (see sourceforge), potential security issues could rise-up very quickly.

Until someone come's up with a better solution, we possibly could utilize `libnss-ldapd` and `slapd` with MySQL/MariaDB as a backend. Those packages are also available and actively maintained in Debian 9 Stretch, see

https://packages.debian.org/de/stretch/libnss-ldapd
https://packages.debian.org/de/stretch/slapd

Kind Regards

**Comment by d00p** [comment]
You do read announcements​ through right?

**Comment by d00p** [comment]
Also, the Webserver and php-fpm/fcgid requires it... froxlor does not, WE are using the guid

**Comment by schallertd** [comment]
> You do read announcements​ through right?
Did miss that one out sorry.

>Also, the Webserver and php-fpm/fcgid requires it... froxlor does not, WE are using the guid
Sorry, forgot about that. Thanks.
