### ISSUE TITLE
Add Stretch to configuration

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#473]
Hello,

I want to suggest adding Stretch to the configuration settings.

Regards,

Af0x

**Comment by d00p** [comment]
It's Planned already, waiting for Dessa - thats why there is no Release yet

**Comment by Commifreak** [comment]
Is there a chance that its done by end of this month? @Dessa

**Comment by ianklemm** [comment]
Is help still needed?
If no, is there an ETA for the next release?

**Comment by d00p** [comment]
Dessa still has no pc at the moment, help is appreciated, as always, no ETA, its done when its done

**Comment by waja** [comment]
> Dessa  still has no pc at the moment, help is appreciated, as always, no ETA, its done when its done

Okay ... what is needed to do by @dessa? Debian packaging skills? Where is help needed?

**Comment by d00p** [comment]
Needed are the configuration-templates (the XML files in lib/configfiles/). I have no time testing all services on a blank box

**Comment by blueJack92** [comment]
I am using Debian Stretch on my productive server already ... I didn't change anything since upgrading to Stretch.

**Comment by d00p** [comment]
> I am using Debian Stretch on my productive server already ... I didn't change anything since upgrading to Stretch.

I highly doubt that...postfix needs changed, fpm just works with mod_proxy, and possible even more changes are needed for other services

**Comment by blueJack92** [comment]
My server is running Debian Stretch without changing the config files ... Apparently I'm lucky!

Von: Michael Kaufmann
Gesendet: Montag, 13. November, 15:32
Betreff: Re: [Froxlor/Froxlor] Add Stretch to configuration (#473)
An: Froxlor/Froxlor
Cc: blueJack92, Comment


I am using Debian Stretch on my productive server already ... I didn't change anything since upgrading to Stretch.
I highly doubt that...postfix needs changed, fpm just works with mod_proxy, and possible even more changes are needed for other services

**Comment by Kourgiantakis** [comment]
Any news regarding that topic?

**Comment by camdenorrb** [comment]
Still need this :/

**Comment by d00p** [comment]
Then i suggest you check the current git master
