### ISSUE TITLE
Feature Request: Support U2F authentication

### ISSUE THREAD

**Issue by MatthiasLohr** [Froxlor/Froxlor#547]
Hello,

i wanted to propose to start a discussion about increased account security. U2F is one (of many) possible standards securing website logins with a second factor. Some big companies like Google, Facebook, etc. already support that. So my proposal is, to include that feature into Froxlor to provide to interested users the possibility to secure their account.

There could also be a new admin feature, which allows to force users to use second factor authentication.

Best regards
Matthias

**Comment by PHPGangsta** [comment]
Yes, that would be nice!
The new webauthn standard is finalized, and supports FIDO U2F, FIDO 2.0, and so on. Support of browsers: Firefox 60+, Chrome 67+, Opera 54+, Edge 18+, Chrome on Android 70.

Please allow each user to create multiple second factors, so a user can add his two U2F devices, one he has in his pocket, and the other one (backup) is in a safe place.

Would be nice if there could be multiple types of second factors, for example "Code via E-Mail", "Code via SMS", "Google Authenticator", and "FIDO U2F via webauthn". Wordpress has a nice plugin called "Two factor", which provides multiple methods for each user:
![smstwlio](https://user-images.githubusercontent.com/608408/48511636-95556300-e857-11e8-8419-c7ed32c3e8c8.png)
https://www.wpbeginner.com/plugins/how-to-add-two-factor-authentication-for-wordpress/
But this plugin only support U2F-Legacy, not webauthn. I just posted it as an example how it could look like in Froxlor.

**Comment by d00p** [comment]
Sounds nice @PHPGangsta - definetly worth a look

**Comment by MatthiasLohr** [comment]
Maybe starting with *everything* is too much. Just do a simple start, with one kind of second factor, e.g. U2F hardware tokens. After the foundation of that is implemented, it's also easier for community members to contribute new methods.
But of course, if you want to do them all right now, feel free :D

**Comment by d00p** [comment]
let's first get done with api-based 0.10.0 version - then see what we can do here :)

**Comment by d00p** [comment]
Like every other version before: when its done

**Comment by MatthiasLohr** [comment]
Actually, you implemented TOTP. That's not U2F. So I would suggest to reopen this ticket.

**Comment by d00p** [comment]
Well, it's two factor authentication...if you're not satisfied with presented  solutions  then please 
feel free to provide a pull request

**Comment by MatthiasLohr** [comment]
If I find the time I will to that.

But since the idea of this ticket was not "any 2FA" but "U2F" it should be reopened (if the feature is desired) - or leave it closed if not. But then is no need for a pull request if it's not desired.

**Comment by PHPGangsta** [comment]
If I see it correctly, a customer or admin can only have 1 second factor, correct? It's normal to have at least 2 second factors, if one dies, or is stolen. That's why Google or Github for example asks you to activate SMS-2FA first, before you can activate any other 2FA method. You always should have 2, if one is lost. You need a backup method, otherwise the account is lost.

I suggest to make it flexible from the beginning that you can have multiple 2FA methods active. Then you don't have problems if you want to have that later on, because then you need to migrate existing data...

For this you need a separate database table, so 1 admin/customer can have multiple 2FA-methods active at the same time. For example two U2F physical devices (or 3?), and TOTP. Or you have 2 separate TOTP devices (1 smartphone and 1 tablet) with separate secrets. That must be possible, otherwise you will have problems in the future.

**Comment by d00p** [comment]
feel free to implement...

**Comment by d00p** [comment]
Nothing happened here in one year, close

**Comment by My1** [comment]
> If I see it correctly, a customer or admin can only have 1 second factor, correct?

when you do U2F you generally have the option to assign multiple U2F/FIDO2 devices and you can use any of those
