### ISSUE TITLE
Missing PHP packages when installing on Debian 9 

### ISSUE THREAD

**Issue by jacubillo** [Froxlor/Froxlor#549]
# Bug

# Summary
Installed froxlor as per wiki instructions on Debian 9 stretch:
apt-get install froxlor -y

When entering the web-install and checking requirements, the following packages where not installed>
php-xml
php-posix
php-mbstring
php-bcmath
php-zip

After a simple apt-get install <missing-packages> the requirements site was ok to continue froxlor install.

Don't know if they should be added to the groupinstall "froxlor" to avoid this.

PS. First time making a bug report. Sorry if this is not required or the proper way to do so.

**Comment by jeensg** [comment]
Just want to add 2 cents, since I ran into these problems with install from repo too:
- php-mysql, php-xml and php-mbstring are absolutely necessary for correct functionality of webserver-app -- mysql for database-connection, mbstring and xml for either configuration page and/or for creating an account from an emailaddress
- php-posix doesn't exist any more, is included in php-common!?
- didn't see anything till right now where php-bcmath and php-zip are necessary, but I believe it might :-)

**Comment by d00p** [comment]
> didn't see anything till right now where php-bcmath and php-zip are necessary, but I believe it might :-)

bcmath is optional and for traffic calculation.
php-zip is for auto-update

**Comment by Dessa** [comment]
php-posix seems to be only a thing on buster
