### ISSUE TITLE
150% ticket usage

### ISSUE THREAD

**Issue by Magissia** [Froxlor/Froxlor#600]
# System information
* Froxlor version: whatever is running on demo site 
* Web server: whatever is running on demo site 
* DNS server: whatever is running on demo site 
* POP/IMAP server: whatever is running on demo site 
* SMTP server: whatever is running on demo site 
* FTP server: whatever is running on demo site 
* OS/Version: ...whatever is running on demo site 

When setting a ticket limit to a reseller and when a customer linked to this reseller open too many tickets, the reseller can exceed it's amount of tickets.

Either customer ticket shouldn't count for the reseller or when resellers ticket credit is exceeded none of it's customers should be able to send tickets.

Same should apply to other metrics.

# Steps to reproduce

1. Set reseller ticket limit to 1
2. Open ticket as customer linked to ticket two times
3. Check dashboard

# Expected behavior

1. Set reseller ticket to 1
2. Customer open first ticket successfully
3. Customer linked to reseller is denied second ticket

# Actual behavior

1. Customer can continue opening ticket when reseller limit is exceeded
2.
3.

# Log files/log entries
syslog:
<pre>
Check your demo server
</pre>

**Comment by d00p** [comment]
Well I think that's because the demo database is filled automatically. The customer has unlimited tickets but is not created from the reseller who would not be able to give the customer unlimited when restricted to one. When setting the demo reseller to have 2 tickets available and trying to add another customer with tickets=unlimited, you'll get: You cannot allocate more resources than you own for yourself.
