### ISSUE TITLE
Incorrect Config Locations for CentOS 7 Apache & ProFTPD

### ISSUE THREAD

**Issue by ufgkirk** [Froxlor/Froxlor#636]
I just wanted to report a few config locations that are incorrect when installing Froxlor on CentOS 7 and going through the System > Configuration wizard.

- The wizard lists /etc/apache2/sites-available/ and /etc/apache2/sites-enabled/ in the CentOS 7 Apache2.4 setup commands.  These folders do not exist by default.  CentOS 7's httpd package installs configs  in /etc/httpd/ and does not make a sites-enabled folder.  

When setting it up I created these folders and added this to my httpd.conf:
`IncludeOptional /etc/apache2/sites-enabled/*.conf`

- The wizard for CentOS 7 ProFTPd lists the configuration location in /etc/proftpd/proftpd.conf.  By default it's just /etc/proftpd.conf on CentOS 7.

When setting it up I just used /etc/proftpd.conf.  Hopefully that's OK and I don't need to inform Froxlor of the different config location somehow.

**Comment by d00p** [comment]
Config paths for webserver are a setting in froxlor (Settings -> Webserver).
For proftpd - you are right, there is no need for froxlor to know the location because this is only used for the initial configuration. So I'd need to adjust that in the config-templates.

Also after reading you issue, I thought about "OS default" files with settings that need changing for the specific distribution and import them upon installation (select box).
