### ISSUE TITLE
Feature Request: Please add the option for domains Under User Dashboard, Under Admin Hosting plans / Add new plan

### ISSUE THREAD

**Issue by s1-ranjan** [Froxlor/Froxlor#644]
By default Froxlor is good to serve one domain per customer but what about with if a customer wants a hosting package with more than one domain? 
So adding an option for domains **Under Admin** Hosting plans / Add new plan would be great, this can add more flexibility to define packages with more than one domain.
Whereas at the user end it would be great to add a circular ring showing the number of the domains that are available / used for the user and an option for managing those domains under User Domain settings will be great to Froxlor.

**Comment by d00p** [comment]
Of course it is possible to use more than 1 domain per customer...the resources in the hosting plans are SUBDOMAINS as only the admins can add main-domains for customers (within his resources)

There is simply no resource "domain" per customer to define how many domains this customer could possibly have (because it's defined by the number of domains the admin/reseller can add).

I know, this would be useful for "real" hosting-plans as the customer pays for specific resources - but froxlor (not even syscp back in the days) does not do it that way....so sorry...not in the near future

**Comment by opuu** [comment]
In my opinion, this feature will make froxlor a way better option than the competition (even some paid ones).
