### ISSUE TITLE
LE breaks Apache

### ISSUE THREAD

**Issue by Af0x** [Froxlor/Froxlor#778]
Hello,

when Froxlor-LE-cron is renewing certificates and LE is running into a rate limit, the whole webserver stops working and shows this error:

> [ssl:emerg] Certificate and private key ### from /path/to/###.crt and /path/to/###.key do not match
[:emerg] Configuration Failed, exiting

Regards,

Af0x

**Comment by d00p** [comment]
Can you try the following patch so (at least) apache will start if that happens?
```diff
diff --git a/lib/Froxlor/Cron/Http/DomainSSL.php b/lib/Froxlor/Cron/Http/DomainSSL.php
index ca4eed73..39fe0839 100644
--- a/lib/Froxlor/Cron/Http/DomainSSL.php
+++ b/lib/Froxlor/Cron/Http/DomainSSL.php
@@ -68,6 +68,11 @@ class DomainSSL
                                'ssl_key_file' => \Froxlor\FileDir::makeCorrectFile($sslcertpath . '/' . $domain['domain'] . '.key')
                        );
 
+                       if (! $this->validateCertificate($ssl_files)) {
+                               \Froxlor\FroxlorLogger::getInstanceOf()->logAction(\Froxlor\FroxlorLogger::CRON_ACTION, LOG_ERR, 'Given SSL private key for ' . $domain['domain'] . ' does not seem to match the certificate. Cannot create ssl-directives');
+                               return;
+                       }
+
                        if (Settings::Get('system.webserver') == 'lighttpd') {
                                // put my.crt and my.key together for lighty.
                                $dom_certs['ssl_cert_file'] = trim($dom_certs['ssl_cert_file']) . "\n" . trim($dom_certs['ssl_key_file']) . "\n";
@@ -112,4 +117,9 @@ class DomainSSL
 
                return;
        }
+
+       private function validateCertificate($ssl_files = array())
+       {
+               return openssl_x509_check_private_key($ssl_files['ssl_cert_file'], $ssl_files['ssl_key_file']);
+       }
 }
```

**Comment by dtugend** [comment]
@d00p This fix will make matters not much better, because your are passing file paths to the validate function you added, while the openssl_x509_... function expects the file contents. So effectively no SSL will pass that check.

I recommend to move the check further down (right before it populates $domains) and use file_get_contents instead (this way you could also verify they have been written to disk correctly), which is what I did, or some other working solution.

**Comment by dtugend** [comment]
What I mean is adding this:
```
                       if (! $this->validateCertificate($ssl_files)) {
                               \Froxlor\FroxlorLogger::getInstanceOf()->logAction(\Froxlor\FroxlorLogger::CRON_ACTION, LOG_ERR, 'Given SSL private key for ' . $domain['domain'] . ' does not seem to match the certificate. Cannot create ssl-directives');
                               return;
                       }
```
before line 106  here:
https://github.com/Froxlor/Froxlor/blob/35c631946d7532729297adee466d20cd0f9d6c81/lib/Froxlor/Cron/Http/DomainSSL.php#L106

And change the second part to this:
```
       private function validateCertificate($ssl_files = array())
       {
               return openssl_x509_check_private_key(file_get_contents($ssl_files['ssl_cert_file']), file_get_contents($ssl_files['ssl_key_file']));
       }
```

Except if you have an better idea / solution.

PS: I am thankful for froxlor and know it's open source and free, but I want to note this is kind of an important problem, since our whole HTTP was down this morning when I woke up, exactly because of this issue :-)

**Comment by d00p** [comment]
I put this there for a reason, because for lighttpd e.g. the `ssl_cert_file` is set to `ssl_cert_file + ssl_key_file` and other changes required for specific webservers

**Comment by dtugend** [comment]
Yes, you are right. Sorry.
What I suggested would break on other setups.

I guess it would have to be checked directly on `$dom_certs` then but at the original location you suggested or https://github.com/Froxlor/Froxlor/blob/35c631946d7532729297adee466d20cd0f9d6c81/lib/Froxlor/Cron/Http/DomainSSL.php#L59 ?

**Comment by d00p** [comment]
L59 or L70 ... doesnt really make a difference but you are right about checking `$dom_certs` as there is the content of the certificates, the `$ssl_files` i wrongly use in the patch is just the paths to the file (where the content will be put later). So, correctly, it should be:

```diff
diff --git a/lib/Froxlor/Cron/Http/DomainSSL.php b/lib/Froxlor/Cron/Http/DomainSSL.php
index ca4eed73..4ccc410d 100644
--- a/lib/Froxlor/Cron/Http/DomainSSL.php
+++ b/lib/Froxlor/Cron/Http/DomainSSL.php
@@ -68,6 +68,11 @@ class DomainSSL
                                'ssl_key_file' => \Froxlor\FileDir::makeCorrectFile($sslcertpath . '/' . $domain['domain'] . '.key')
                        );
 
+                       if (! $this->validateCertificate($dom_certs)) {
+                               \Froxlor\FroxlorLogger::getInstanceOf()->logAction(\Froxlor\FroxlorLogger::CRON_ACTION, LOG_ERR, 'Given SSL private key for ' . $domain['domain'] . ' does not seem to match the certificate. Cannot create ssl-directives');
+                               return;
+                       }
+
                        if (Settings::Get('system.webserver') == 'lighttpd') {
                                // put my.crt and my.key together for lighty.
                                $dom_certs['ssl_cert_file'] = trim($dom_certs['ssl_cert_file']) . "\n" . trim($dom_certs['ssl_key_file']) . "\n";
@@ -112,4 +117,9 @@ class DomainSSL
 
                return;
        }
+
+       private function validateCertificate($dom_certs = array())
+       {
+               return openssl_x509_check_private_key($dom_certs['ssl_cert_file'], $dom_certs['ssl_key_file']);
+       }
 }
```

**Comment by RipClaw2971** [comment]
I ran into the same problem. This is my patch for it:

```
diff --git a/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php b/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
index 2515783a..d781d55a 100644
--- a/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
+++ b/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
@@ -18,9 +18,9 @@ use Froxlor\Database\Database;
  * @author Froxlor team <team@froxlor.org> (2016-)
  * @license GPLv2 http://files.froxlor.org/misc/COPYING.txt
  * @package Cron
- *         
+ *
  * @since 0.9.35
- *       
+ *
  */
 class AcmeSh extends \Froxlor\Cron\FroxlorCron
 {
@@ -350,7 +350,7 @@ class AcmeSh extends \Froxlor\Cron\FroxlorCron
 			$return = array();
 			self::readCertificateToVar($certrow['domain'], $return);
 
-			if (! empty($return['crt'])) {
+			if ((! empty($return['crt'])) && (openssl_x509_check_private_key($return['crt'],$return['key']))) {
 
 				$newcert = openssl_x509_parse($return['crt']);
```
 This prevents the certificate from being imported.

**Comment by d00p** [comment]
Also very nice yes, additionally, my solutions prevents issues with customer-specified certificates too (if possible at all)

**Comment by kroimon** [comment]
I understand that this will ignore mismatching or invalid keys and certificates. But will froxlor try to get new LE certificates after some time?
Why are these mismatching certificates created by acme.sh in the first place? Or why are they imported into froxlor if they are not valid?

**Comment by d00p** [comment]
> Why are these mismatching certificates created by acme.sh in the first place? 

That's something I was not able to reproduce yet as I myself did never run into this issue

> Or why are they imported into froxlor if they are not valid?

Well I kinda was naiv enough to think, if I get a positive response via ACME it should be a valid certificate...maybe we should check more there, yes

**Comment by dtugend** [comment]
I tried to find some hints what caused it, including going through server backups before and after, but it's pretty difficult for me, especially since there's quite some automated hacking attempts going on on some of the sites, so it's hard to tell apart from the noise.

The Froxlor system log is pretty silent for ~4 days prior the incident and then only has results of my actions.

The only notable change before that was updating to the latest Froxlor version at the time.

On December 27th 06:50:20 GMT+1 for some reason the Apache 2.4 other vhosts logs show a lot of acme challenge requests for many of the domains hosted on the server.
Those stopped at 07:01:47 GMT+1, at 07:01:54 GMT+1 the error log shows the apache was restartet and had 1x AH00020 and after that a few AH00016 errors and it was dead since then until I intervened.

**So I am guessing it just hit the limit and the old certificates were in non-proper state / screwed somehow, as OP described.**

The interesting part is that we have another server and that server decided to renew it's Let's Encrypt certificates around the same time, the first one is issued 06:05:00 GMT+1 on 27th December 2019.

I had updated both servers on 16th December to Froxlor 0.10.10.zip.

**So my guess is that something or maybe even Let's Encrypt themselves triggered a renewal of the certificates, but I found no hints in Google if anyone else is affected.**

**Comment by d00p** [comment]
Thanks for digging into this, I myself was also not able to find the REAL cause, still the best guess would be a possible error/rate limit but still a private key was generated/stored and then no valid public key for it or something like that
