### ISSUE TITLE
FR: Optional web shell

### ISSUE THREAD

**Issue by jucajuca** [Froxlor/Froxlor#805]
# Feature request

# Summary

In many networks ports are blocked and tweaking things in the server without shell access becomes impossible. 

It would be very nice to have an shell access through froxlor. There are solutions that can be integrated such as PHP shell. This feature might be optional.

**Comment by discordier** [comment]
To put it up simple... for security considerations... NOOOOOOO, please not.

He who needs to tweak these things has SSH access, he who does not have SSH will never have the power to tweak such things.

In all my years (started running my servers in the end 90s) I have never needed a web shell but have had many occurences where customers and websites got infected with one.

Web shells bear many problems while solving no problem at all but work around symptoms of a bigger problem in entirely unrelated fields (in this case, the firewall problems of the OP are better solved by using a VPN instead of running a shell via browser).

**Comment by d00p** [comment]
I agree with @discordier ...if you want, install php-shell scripts, but I won't integrate something like that.
