### ISSUE TITLE
Domain list sorting order (IDN issue)

### ISSUE THREAD

**Issue by net44** [Froxlor/Froxlor#809]
# Summary
Since few months, domain list under Admin account does not work/sort properly if you have IDN domain/s. All IDN domains are always ordered under "x" letter. For example : 

**_Domains should be in that order_** :

- köln.tld
- stuttgart.tld
- würzburg.tld
- wyoming.tld

**_but they are sorted in that order_** :

- stuttgart.tld
- wyoming.tld
- köln.tld (xn--kln-sna.tld)
- würzburg.tld (xn--wrzburg-n2a.tld)

It worked very well before and sorting domains alphabetically was correct. 

It is correct but only under Dashboard and under customer account, under Domain settings and under Email Addresses alphabetical sorting not working too.

# System information
* Froxlor version: latest release downloaded from github / 15 Feb 2020
* Web server: apache2
* DNS server: Bind
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd
* OS/Version: Deb10

**Comment by d00p** [comment]
Problem is, the domains are stored in punycode (if applicable) and sql/mysql does not know how to convert so sorting can only be done after reading from mysql which is kinda bad because this messes up pagination and sorting which is done directly with sql (0.9.x did that differently yes).

So, in order to fix this I'd need to add another field to the domains table, where all the domain names are stored in IDN to have a correct sorting.
