### ISSUE TITLE
Ubuntu Repo not working (404)

### ISSUE THREAD

**Issue by zietbukuel** [Froxlor/Froxlor#810]
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

```
# apt update
Hit:1 http://archive.canonical.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Ign:5 https://deb.froxlor.org/debian bionic InRelease
Err:6 https://deb.froxlor.org/debian bionic Release
  404  Not Found [IP: 2a01:440:1:12:82:149:225:211 443]
Reading package lists... Done
E: The repository 'https://deb.froxlor.org/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by d00p** [comment]
Well, then don't enter `debian` on an Ubuntu system, it's on our wiki (https://github.com/Froxlor/Froxlor/wiki/Install-froxlor-on-ubuntu), for Ubuntu use: https://deb.froxlor.org/ubuntu

**Comment by MarvelousMari** [comment]
I'm also having this issue, the code on the Ubuntu page isn't the best. I've found the issue
`wget -O - https://deb.froxlor.org/froxlor.gpg | apt-key add -`
Doesn't work, the - at the end doesn't actually add it. According to it's man page and --help "-" should work but doesn't for some reason.

You can break up the command to this
`wget -O - https://deb.froxlor.org/froxlor.gpg > my.key`
`apt-key add my.key`
`rm my.key`
Which should work

After that you'll wanna change what gets put into the .list file is different. I haven't had time to decifer the man [pages](https://manpages.ubuntu.com/manpages/precise/en/man5/sources.list.5.html) but even though both `lsb_release -sc` and `focal` are the same value in the .list file if you use the suggested command
`echo "deb https://deb.froxlor.org/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/froxlor.list`
the `$(lsb_release -sc)` causes apt to not be able to find the Release file. Instead replace `$(lsb_release -sc)` with what that evaluates to in your terminal, in my case the command is
`echo "deb https://deb.froxlor.org/ubuntu focal main" > /etc/apt/sources.list.d/froxlor.list`

This isn't ideal because it's hardcoded but it works after that.

**Comment by d00p** [comment]
Just did an installation on focal last week, worked flawlessly. Also you did not provide any error message or log entries just "doesn't work". 
Did you folow the wiki? Did you install the requirements? Anyway, old issue. For support please use the forum at http://forum.froxlor.org

**Comment by MarvelousMari** [comment]
sorry, didn't have enough time to go more in depth, decided to just post a solution.

`wget -O - https://deb.froxlor.org/froxlor.gpg | apt-key add -`  results in
`--2021-03-23 16:09:09--  https://deb.froxlor.org/froxlor.gpg
Resolving deb.froxlor.org (deb.froxlor.org)... E: This command can only be used by root.
185.123.52.110, 2a10:ec2::185:123:52:110
Connecting to deb.froxlor.org (deb.froxlor.org)|185.123.52.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2018 (2.0K)
Saving to: ‘STDOUT’

-                     0%[                   ]       0  --.-KB/s    in 0s      


Cannot write to ‘-’ (Success).
`
but writing the key to file does work.

Additionally the froxlor.list file when it has 
`deb https://deb.froxlor.org/ubuntu $(lsb_release -sc) main`
as it's contents and you attempt to update
`sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Ign:5 https://deb.froxlor.org/ubuntu $(lsb_release InRelease       
Err:6 https://deb.froxlor.org/ubuntu $(lsb_release Release
  404  Not Found [IP: 185.123.52.110 443]
Reading package lists... Done
E: The repository 'https://deb.froxlor.org/ubuntu $(lsb_release Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
Which prevents you from installing. If you change the contents of `/etc/apt/sources.list.d/froxlor.list` to
`deb https://deb.froxlor.org/ubuntu focal main` 
you can now update and install. But hardcoding `focal` or whatever edition of Ubuntu you're using instead of using `$(lsb_release -sc)` isn't ideal.

**Comment by d00p** [comment]
Well, the error message says it all: __E: This command can only be used by root.__

You are supposed to run all this as root

**Comment by MarvelousMari** [comment]
Yeah you're right sorry about that one. The issue with `$(lsb_release -sc)` is still a problem though

**Comment by d00p** [comment]
Well you do not enter

`deb https://deb.froxlor.org/ubuntu $(lsb_release -sc) main`

in your apt-sources but execute the whole command

`echo "deb https://deb.froxlor.org/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/froxlor.list`

see example output of shell here:

```
root@adc-e15:/home/d00p# echo "deb https://deb.froxlor.org/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/froxlor.list
root@adc-e15:/home/d00p# cat /etc/apt/sources.list.d/froxlor.list
deb https://deb.froxlor.org/ubuntu groovy main
```

**Comment by MarvelousMari** [comment]
Welp that make sense, thanks!
