### ISSUE TITLE
Performerce improvment

### ISSUE THREAD

**Issue by tczaude** [Froxlor/Froxlor#868]
# Summary

Analize slowlog from mysql i find some lacks in queries which not have indexes or not use it correctly. 
Problem is when system is high loaded this can produce many queries. In example from 3 weeks a have 6 milions entries. 
This values can be deferend base on how company work and use mails etc.
 As first part 

`
ALTER TABLE `froxlor`.`panel_customers` ADD INDEX `guid` (`guid`);

ALTER TABLE `froxlor`.`mail_users` ADD INDEX `username` (`username`); 

ALTER TABLE `froxlor`.`mail_users` ADD INDEX `imap` (`imap`);

ALTER TABLE `froxlor`.`mail_users` ADD INDEX `pop3` (`pop3`);

ALTER TABLE `froxlor`.`panel_tasks` ADD INDEX `type` (`type`); 

ALTER TABLE `froxlor`.`ftp_groups` ADD INDEX `gid` (`gid`); 

ALTER TABLE `froxlor`.`ftp_groups` ADD INDEX `members` (`members`); 
`
next in code we have

`SELECT COUNT(*) as jobcnt FROM `panel_tasks``

this not use indexes 
probably can be replaced by

`SELECT COUNT(id) as jobcnt FROM `panel_tasks``

**Comment by d00p** [comment]
Pull requests are very welcome :)

**Comment by tczaude** [comment]
ok i try find more examples in case and try make this migrations via pull request.

**Comment by tczaude** [comment]
where is stored migrations  for db ?

**Comment by d00p** [comment]
All database-related updates are here: https://github.com/Froxlor/Froxlor/blob/master/install/updates/froxlor/0.10/update_0.10.inc.php

In order to "trigger" them, you need to increase the database-version number, which is defined here: https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/Froxlor.php#L13

You will also have to set the db-version in the froxlor.sql for new installations so they have the correct (current) one, see: https://github.com/Froxlor/Froxlor/blob/master/install/froxlor.sql#L708

**Comment by d00p** [comment]
refs #871

**Comment by tczaude** [comment]
thanks I will continue to monitor the situation

**Comment by d00p** [comment]
`A database error occurred
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'members' used in key specification without a key length`
