### ISSUE TITLE
API: Traffic.listing parameter loginname is ignored

### ISSUE THREAD

**Issue by andlinger** [Froxlor/Froxlor#894]
When listening traffic via API, the parameter loginname is ignored. Only customerid works

**Comment by d00p** [comment]
Works perfectly fine; maybe you forgot the `customer_traffic` parameter to be set to 1 (else you will just see the complete traffic of the admin which is not divisable in customers)

**Comment by andlinger** [comment]
Works!
Why do I need the parameter "customer_traffic"?
Why is the customer traffic not simply returned if "customerid" or "loginname" is set?

**Comment by d00p** [comment]
by design. Traffic is being stored per customer and then the sum of all customers is stored for the admin (not really necessary as it could be calculated on the fly but that's the current code). So as I said, if you do not explicitly tell the command to check customer traffic it will just return the traffic of the function calling admin.
