### ISSUE TITLE
add support litespeed (http/3, QUIC)

### ISSUE THREAD

**Issue by TOWUK** [Froxlor/Froxlor#943]
its just feature request from forums froxlor

**Comment by d00p** [comment]
I don't see a big target group for that...supporting a new webserver is quite a big thing

**Comment by Dessa** [comment]
there is more to that too:
1 ) having an openssl version to support QUIC ( 3.0 will not, to my knowledge ); im aware that there are openssl forks and also GnuTLS 
2 ) having apache / nginx support it, for the former the only http related apache project that i could find in my 5 minute search is trafficserver, the latter has a branch and has had a target milestone since 1.17, 1.21 just branched off today; still doesn't have it.
3 ) having these package versions *actually in the main repository*

so expect this to be open for a *long* time.

**Comment by webhosting24** [comment]
Litespeed is compatible with Apache, there are differences in mod_security, but everything else *should* be easy, including .htaccess-support. OpenLitespeed is something else, there you do not have .htaccess compatibility etc.
