### ISSUE TITLE
After froxlor package update, no letsencrypt certificates are renewed

### ISSUE THREAD

**Issue by martinsteldinger** [Froxlor/Froxlor#951]
# Summary

After a package update on Debian, the cronjobs are not running any longer since froxlor wants the admin to have the databases updated from the web interface. This is not good in regards to the letsencrypt certificates which can expire.

# System information
* Froxlor version: 0.10.25 -> 0.10.26
* OS/Version: Debian Buster

# Steps to reproduce

1. install older version of froxlor
2. update to a newer froxlor
3. run letsencrypt cronjob by hand to see the log on failed certificate creation 

# Expected behavior

1. have older version of froxlor installed
2. update to a newer version of froxlor
3. the certificates are generated when expired

# Actual behavior

1. have older version of froxlor installed
2. update to a newer version of froxlor
3. the cronjob on letsencrypt certificates are not running since a database update is required by admin on a web interface

**Comment by d00p** [comment]
I cant quite follow you, if you update the files you have to login to run the rest of the update process. It's been like this since day 1, not between 0.10.25 and 0.10.26

You can enable automatic database updates via cronjob in `Settings -> Cronjob settings -> Allow automatic database updates` if you do not want to have to manually run through the update process - not recommended though.
